config/routes.rb
AnimatedType::Application.routes.draw do
  resources :designs

end

app/models/design.rb
class Design < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController
  # before_action :set_design, only: [:show, :edit, :update, :destroy]

  # GET /designs
  # GET /designs.json
  def index
    @designs = Design.all
  end
end

#   # GET /designs/1
#   # GET /designs/1.json
#   def show
#   end

#   # GET /designs/new
#   def new
#     @design = Design.new
#   end

#   # GET /designs/1/edit
#   def edit
#   end

#   # POST /designs
#   # POST /designs.json
#   def create
#     @design = Design.new(design_params)

#     respond_to do |format|
#       if @design.save
#         format.html { redirect_to @design, notice: 'Design was successfully created.' }
#         format.json { render action: 'show', status: :created, location: @design }
#       else
#         format.html { render action: 'new' }
#         format.json { render json: @design.errors, status: :unprocessable_entity }
#       end
#     end
#   end

#   # PATCH/PUT /designs/1
#   # PATCH/PUT /designs/1.json
#   def update
#     respond_to do |format|
#       if @design.update(design_params)
#         format.html { redirect_to @design, notice: 'Design was successfully updated.' }
#         format.json { head :no_content }
#       else
#         format.html { render action: 'edit' }
#         format.json { render json: @design.errors, status: :unprocessable_entity }
#       end
#     end
#   end

#   # DELETE /designs/1
#   # DELETE /designs/1.json
#   def destroy
#     @design.destroy
#     respond_to do |format|
#       format.html { redirect_to designs_url }
#       format.json { head :no_content }
#     end
#   end

#   private
#     # Use callbacks to share common setup or constraints between actions.
#     def set_design
#       @design = Design.find(params[:id])
#     end

#     # Never trust parameters from the scary internet, only allow the white list through.
#     def design_params
#       params[:design]
#     end
# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/designs_helper.rb
module DesignsHelper
end

app/views/designs/_form.html.erb
<%= form_for(@design) do |f| %>
  <% if @design.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@design.errors.count, "error") %> prohibited this design from being saved:</h2>

      <ul>
      <% @design.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/designs/edit.html.erb
<h1>Editing design</h1>

<%= render 'form' %>

<%= link_to 'Show', @design %> |
<%= link_to 'Back', designs_path %>

app/views/designs/index.html.erb
<ul class="grid">
    <li class="ot-letter-left"><span data-letter="T">T</span></li>
    <li class="ot-letter-top"><span data-letter="H">H</span></li>
    <li class="ot-letter-right"><span data-letter="I">I</span></li>
    <li class="ot-letter-bottom"><span data-letter="S">S</span>
    <li class="ot-letter-left"><span data-letter="I">I</span></li>
    <li class="ot-letter-top"><span data-letter="S">S</span></li>
    <li class="ot-letter-right"><span data-letter="A">A</span></li>
    <li class="ot-letter-bottom"><span data-letter="N">N</span></li>
    <li class="ot-letter-left"><span data-letter="I">I</span></li>
    <li class="ot-letter-top"><span data-letter="M">M</span></li> 
    <li class="ot-letter-right"><span data-letter="A">A</span></li>
    <li class="ot-letter-bottom"><span data-letter="T">T</span></li>
    <li class="ot-letter-left"><span data-letter="E">E</span></li>
    <li class="ot-letter-top"><span data-letter="D">D</span></li>
    <li class="ot-letter-right"><span data-letter="T">T</span></li>
    <li class="ot-letter-bottom"><span data-letter="E">E</span></li> 
    <li class="ot-letter-left"><span data-letter="X">X</span></li>
    <li class="ot-letter-top"><span data-letter="T">T</span></li>
</ul>


<% content_for 'extra_footer' do %>
 <% end %> 

app/views/designs/new.html.erb
<h1>New design</h1>

<%= render 'form' %>

<%= link_to 'Back', designs_path %>

app/views/designs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_design_path(@design) %> |
<%= link_to 'Back', designs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AnimatedType</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<%= yield 'extra_footer' %>

</body>
</html>